apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyhttp
spec:
  selector:
    matchLabels:
      app: pyhttp
  replicas: 1 
  template:
    metadata:
      labels:
        app: pyhttp
    spec:
      containers:
      - name: pyhttp-container
        image: unixutils/pyhttp:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 7000
        env:
        - name: PYHTTP_KEY_FROM_CONFIGMAP
          valueFrom:
            configMapKeyRef:
              name: pyhttpcmap
              key: pyhttpCmKey
        - name: PYHTTP_KEY_FROM_DATA_SECRET
          valueFrom:
            secretKeyRef:
              name: pyhttpsecret
              key: pyhttpDataSecret
        - name: PYHTTP_KEY_FROM_STRING_DATA_SECRET
          valueFrom:
            secretKeyRef:
              name: pyhttpsecret 
              key: pyhttpStringDataSecret
        volumeMounts:
          - name: pyhttpvolume-from-configmap
            mountPath: "/pyhttp_configmap/"
            readOnly: true
          - name: pyhttpvolume-from-secret
            mountPath: "/pyhttp_secret/"
          - name: pyhttp-projected-volume
            mountPath: "/pyhttp_projected_volume"
      volumes:
      - name: pyhttpvolume-from-configmap
        configMap:
          name: pyhttpcmap # name of the configmapt that was created
          items:
          - key: pyhttpCmapFile # file like key in configmap
            path: PYHTTP_FILE_FROM_CONFIGMAP # name of the file to mount the value from key as.
      - name: pyhttpvolume-from-secret
        secret: 
          secretName: pyhttpsecret
          items:
           - key: pyhttpStringDataSecretMultiLine
             path: PYHTTP_FILE_FROM_SECRET
      - name: pyhttp-projected-volume
        projected:
          sources:
          - secret: 
              name: pyhttpsecret
              items:
               - key: pyhttpStringDataSecretMultiLine
                 path: PYHTTP_FILE_FROM_SECRET
          - configMap:
              name: pyhttpcmap
              items:
               - key: pyhttpCmapFile
                 path: PYHTTP_FILE_FROM_CONFIGMAP
